import mongoose from "mongoose";
import dotenv from "dotenv";
import Cropdata from "../models/Cropdata.js";
// Removed incorrect import of Crops.jsx (frontend file)

dotenv.config();

const keralaCrops = [
  {
    cropType: "kharif",
    imageLink: "https://wallpapercave.com/wp/wp3069392.jpg",
    cropName: "Paddy",
    soilType: "loamy",
    description: "Kerala's most important food crop, requiring abundant water for its three main growing seasons.",
    optimalSoilPH: 6.5,
    minimumTemp: 20,
    maximumTemp: 35,
    minimumHumidity: 65,
    maximumHumidity: 90,
    optimalSunlightHours: 7,
    minimumRainfall: 200,
    maximumRainfall: 400,
    commonPests: ["Brown plant hopper", "Gall midge"],
    commonDiseases: ["Blast", "Sheath blight"],
    price: 40
  },
  {
    cropType: "perennial",
    imageLink: "https://tse4.mm.bing.net/th/id/OIP.xlZaxv532TZpKh7y3C_vsAHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
    cropName: "Coconut",
    soilType: "sandy",
    description: "Widely grown along the coast; used for coir, oil, and culinary purposes.",
    optimalSoilPH: 6,
    minimumTemp: 18,
    maximumTemp: 32,
    minimumHumidity: 65,
    maximumHumidity: 85,
    optimalSunlightHours: 7,
    minimumRainfall: 180,
    maximumRainfall: 300,
    commonPests: ["Rhinoceros beetle", "Red palm weevil"],
    commonDiseases: ["Bud rot", "Stem bleeding"],
    price: 35
  },
  {
    cropType: "perennial",
    imageLink: "https://www.rainforest-alliance.org/wp-content/uploads/2021/06/rubber-tree-tapping-square-1-1024x1024.jpg",
    cropName: "Rubber",
    soilType: "clayey",
    description: "A mainstay plantation crop in Kerala’s hilly regions, providing latex for industry.",
    optimalSoilPH: 5.5,
    minimumTemp: 20,
    maximumTemp: 34,
    minimumHumidity: 70,
    maximumHumidity: 90,
    optimalSunlightHours: 8,
    minimumRainfall: 150,
    maximumRainfall: 250,
    commonPests: ["Termites", "Scale insects"],
    commonDiseases: ["Powdery mildew", "Leaf spot"],
    price: 110
  },
  {
    cropType: "perennial",
    imageLink: "https://cdn.permacultureplants.com/wp-content/uploads/black-pepper-spice-plant-1024x544.jpg",
    cropName: "Black Pepper",
    soilType: "lateritic",
    description: "Kerala produces India’s finest pepper, notable for aroma and pungency.",
    optimalSoilPH: 6.5,
    minimumTemp: 20,
    maximumTemp: 30,
    minimumHumidity: 65,
    maximumHumidity: 85,
    optimalSunlightHours: 7,
    minimumRainfall: 150,
    maximumRainfall: 300,
    commonPests: ["Pollu beetle", "Stem borer"],
    commonDiseases: ["Quick wilt", "Anthracnose"],
    price: 580
  },
  {
    cropType: "perennial",
    imageLink: "https://img.freepik.com/premium-photo/close-up-green-cardamom-plant_698417-1964.jpg?w=2000",
    cropName: "Cardamom",
    soilType: "forest loam",
    description: "A valuable spice grown in the humid hills; called the 'Queen of Spices'.",
    optimalSoilPH: 5.5,
    minimumTemp: 15,
    maximumTemp: 30,
    minimumHumidity: 80,
    maximumHumidity: 90,
    optimalSunlightHours: 6,
    minimumRainfall: 150,
    maximumRainfall: 350,
    commonPests: ["Thrips", "Shoot borer"],
    commonDiseases: ["Capsule rot", "Mosaic virus"],
    price: 2350
  },
  {
    cropType: "kharif",
    imageLink: "https://tse4.mm.bing.net/th/id/OIP.5e9lNfwhBge8ZG_LsaurFwHaE7?rs=1&pid=ImgDetMain&o=7&rm=3",
    cropName: "Banana",
    soilType: "alluvial",
    description: "Grown year-round for fruit and leaves used in Kerala’s cuisine and rituals.",
    optimalSoilPH: 6.5,
    minimumTemp: 24,
    maximumTemp: 35,
    minimumHumidity: 60,
    maximumHumidity: 95,
    optimalSunlightHours: 6,
    minimumRainfall: 150,
    maximumRainfall: 300,
    commonPests: ["Banana weevil", "Aphids"],
    commonDiseases: ["Panama wilt", "Sigatoka leaf spot"],
    price: 38
  },
  {
    cropType: "zaid",
    imageLink: "https://www.gardeningknowhow.com/wp-content/uploads/2016/01/cashew-fruit-hanging-on-tree.jpg",
    cropName: "Cashew Nut",
    soilType: "sandy",
    description: "A commercial crop, both nut and fruit are processed and exported from Kerala.",
    optimalSoilPH: 6,
    minimumTemp: 20,
    maximumTemp: 35,
    minimumHumidity: 55,
    maximumHumidity: 80,
    optimalSunlightHours: 7,
    minimumRainfall: 100,
    maximumRainfall: 250,
    commonPests: ["Tea mosquito bug"],
    commonDiseases: ["Powdery mildew"],
    price: 670
  },
  {
    cropType: "kharif",
    imageLink: "https://tse2.mm.bing.net/th/id/OIP.HYWxGq-7Id7exMu6WXaRwQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
    cropName: "Mango",
    soilType: "loamy",
    description: "Seasonal fruit crop, common in Kerala’s home gardens; many local varieties.",
    optimalSoilPH: 6,
    minimumTemp: 22,
    maximumTemp: 40,
    minimumHumidity: 50,
    maximumHumidity: 80,
    optimalSunlightHours: 8,
    minimumRainfall: 75,
    maximumRainfall: 250,
    commonPests: ["Fruit flies", "Mango hoppers"],
    commonDiseases: ["Powdery mildew", "Anthracnose"],
    price: 55
  },
  {
    cropType: "kharif",
    imageLink: "https://tse1.mm.bing.net/th/id/OIP.MP-jTtZqGQg9RndVFB3nfQHaE9?rs=1&pid=ImgDetMain&o=7&rm=3",
    cropName: "Pineapple",
    soilType: "lateritic",
    description: "Extensively cultivated in Kerala; ‘Mauritius’ is a popular local variety.",
    optimalSoilPH: 5.5,
    minimumTemp: 20,
    maximumTemp: 32,
    minimumHumidity: 50,
    maximumHumidity: 80,
    optimalSunlightHours: 7,
    minimumRainfall: 120,
    maximumRainfall: 250,
    commonPests: ["Mealy bugs", "Nematodes"],
    commonDiseases: ["Heart rot", "Wilt"],
    price: 35
  },
  {
    cropType: "perennial",
    imageLink: "https://tse1.explicit.bing.net/th/id/OIP.x2Jr5qK9mP6r5WxpfEihYQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
    cropName: "Jackfruit",
    soilType: "lateritic",
    description: "Large, nutritious fruit grown statewide; tender jackfruit is used as a vegetable.",
    optimalSoilPH: 6.5,
    minimumTemp: 24,
    maximumTemp: 38,
    minimumHumidity: 60,
    maximumHumidity: 80,
    optimalSunlightHours: 7,
    minimumRainfall: 100,
    maximumRainfall: 300,
    commonPests: ["Fruit flies", "Bark caterpillar"],
    commonDiseases: ["Fruit rot", "Stem rot"],
    price: 25
  },
  {
    cropType: "perennial",
    imageLink: "https://www.thespruce.com/thmb/eSUvtvcFvhRP_NFDNCUrvLzBfD4=/2423x1236/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-1040481988-6b35986370b7478db32d1e7c5ba77548.jpg",
    cropName: "Tea",
    soilType: "acidic",
    description: "Tea is grown in hill stations like Munnar and Wayanad, Kerala.",
    optimalSoilPH: 5.5,
    minimumTemp: 15,
    maximumTemp: 30,
    minimumHumidity: 70,
    maximumHumidity: 90,
    optimalSunlightHours: 6,
    minimumRainfall: 150,
    maximumRainfall: 300,
    commonPests: ["Tea mosquito bug", "Looper caterpillar"],
    commonDiseases: ["Blister blight", "Red rust"],
    price: 140
  },
  {
    cropType: "perennial",
    imageLink: "https://th.bing.com/th/id/OIP.NNIMMa3_kef0dtiQN9zNFAHaE7?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
    cropName: "Arecanut",
    soilType: "lateritic",
    description: "Used as a masticatory whole-plant product and economically vital for farmers.",
    optimalSoilPH: 6.0,
    minimumTemp: 22,
    maximumTemp: 35,
    minimumHumidity: 60,
    maximumHumidity: 90,
    optimalSunlightHours: 8,
    minimumRainfall: 120,
    maximumRainfall: 300,
    commonPests: ["Mites", "Red palm weevil"],
    commonDiseases: ["Fruit rot", "Yellow leaf disease"],
    price: 175
  },
  {
    cropType: "kharif",
    imageLink: "https://www.thespruce.com/thmb/FS2cZMdfQNwM77N-yplVQbrfyjM=/2000x1500/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-1174305372-718fb182f53b4714bd0789d8a312d66f.jpg",
    cropName: "Coffee",
    soilType: "forest loam",
    description: "Chik coffee plantations are gaining ground in Kerala’s upland districts.",
    optimalSoilPH: 5.5,
    minimumTemp: 15,
    maximumTemp: 28,
    minimumHumidity: 70,
    maximumHumidity: 90,
    optimalSunlightHours: 7,
    minimumRainfall: 120,
    maximumRainfall: 250,
    commonPests: ["Coffee borer beetle", "Berry borer"],
    commonDiseases: ["Leaf rust", "Anthracnose"],
    price: 250
  },
  {
    cropType: "kharif",
    imageLink: "https://cdn.mos.cms.futurecdn.net/kRqwjJiWyETykC63GRe2kh.jpg",
    cropName: "Tapioca",
    soilType: "lateritic",
    description: "Tapioca tubers are used for food products; popular in many rural homes.",
    optimalSoilPH: 6.0,
    minimumTemp: 22,
    maximumTemp: 35,
    minimumHumidity: 60,
    maximumHumidity: 90,
    optimalSunlightHours: 8,
    minimumRainfall: 120,
    maximumRainfall: 200,
    commonPests: ["Scale insects", "Mealybug"],
    commonDiseases: ["Cassava mosaic virus"],
    price: 22
  },
  {
    cropType: "zaid",
    imageLink: "https://cdn.mos.cms.futurecdn.net/kRqwjJiWyETykC63GRe2kh.jpg",
    cropName: "Sweet Potato",
    soilType: "loamy",
    description: "Cultivated in homesteads and fields in Kerala; leaves edible as greens.",
    optimalSoilPH: 6,
    minimumTemp: 21,
    maximumTemp: 30,
    minimumHumidity: 65,
    maximumHumidity: 95,
    optimalSunlightHours: 7,
    minimumRainfall: 100,
    maximumRainfall: 230,
    commonPests: ["Sweet potato weevil", "Aphids"],
    commonDiseases: ["Root rot", "Black rot"],
    price: 35
  },
  {
    cropType: "zaid",
    imageLink: "https://tse1.explicit.bing.net/th/id/OIP.5z_6DKrEBUcmQePB4cG5VwHaE7?rs=1&pid=ImgDetMain&o=7&rm=3",
    cropName: "Yam",
    soilType: "loamy",
    description: "Tuber crop, widely used as a substitute for cereals; high yielding.",
    optimalSoilPH: 6.5,
    minimumTemp: 23,
    maximumTemp: 32,
    minimumHumidity: 63,
    maximumHumidity: 92,
    optimalSunlightHours: 7,
    minimumRainfall: 110,
    maximumRainfall: 230,
    commonPests: ["Nematodes", "White grubs"],
    commonDiseases: ["Leaf spot", "Tuber rot"],
    price: 38
  },
  {
    cropType: "kharif",
    imageLink: "https://healthiersteps.com/wp-content/uploads/2022/07/yam-plant-garden.jpeg",
    cropName: "Pumpkin",
    soilType: "sandy",
    description: "Common vegetable crop grown in homesteads, cooked in various recipes.",
    optimalSoilPH: 6.2,
    minimumTemp: 22,
    maximumTemp: 30,
    minimumHumidity: 60,
    maximumHumidity: 80,
    optimalSunlightHours: 7,
    minimumRainfall: 90,
    maximumRainfall: 160,
    commonPests: ["Fruit fly", "Aphids"],
    commonDiseases: ["Powdery mildew", "Downy mildew"],
    price: 20
  },
  {
    cropType: "zaid",
    imageLink: "https://th.bing.com/th/id/OIP.zQEGlbRHHFuf5QUDxTHfMQHaEA?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
    cropName: "Cucumber",
    soilType: "sandy",
    description: "Climatic vegetables grown in Kerala, especially in summer in polyhouses.",
    optimalSoilPH: 6.2,
    minimumTemp: 22,
    maximumTemp: 34,
    minimumHumidity: 60,
    maximumHumidity: 85,
    optimalSunlightHours: 7,
    minimumRainfall: 95,
    maximumRainfall: 140,
    commonPests: ["Cucumber beetle", "Thrips"],
    commonDiseases: ["Powdery mildew", "Downy mildew"],
    price: 25
  },
  {
    cropType: "kharif",
    imageLink: "https://tse3.mm.bing.net/th/id/OIP.gJyDjf_0Wg0jDkt2DQ2W7AHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
    cropName: "Bitter Gourd",
    soilType: "loamy",
    description: "Valued for its medicinal properties and taste in Kerala cuisine.",
    optimalSoilPH: 6.4,
    minimumTemp: 19,
    maximumTemp: 32,
    minimumHumidity: 60,
    maximumHumidity: 82,
    optimalSunlightHours: 7,
    minimumRainfall: 90,
    maximumRainfall: 180,
    commonPests: ["Fruit fly", "Red pumpkin beetle"],
    commonDiseases: ["Powdery mildew", "Downy mildew"],
    price: 35
  },
  {
    cropType: "kharif",
    imageLink: "https://tse2.mm.bing.net/th/id/OIP.Xc4F55AvFU6M9CAF1UevCQHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
    cropName: "Snake Gourd",
    soilType: "loamy",
    description: "Long-fruited vegetable, common in homestead and field gardens across Kerala.",
    optimalSoilPH: 6.0,
    minimumTemp: 21,
    maximumTemp: 34,
    minimumHumidity: 60,
    maximumHumidity: 84,
    optimalSunlightHours: 6,
    minimumRainfall: 80,
    maximumRainfall: 160,
    commonPests: ["Fruit fly", "Aphids"],
    commonDiseases: ["Downy mildew", "Powdery mildew"],
    price: 42
  },
  {
    cropType: "kharif",
    imageLink: "https://tse4.mm.bing.net/th/id/OIP.KPN-FJ6TJy3IhLcScEgkRAHaFN?rs=1&pid=ImgDetMain&o=7&rm=3",
    cropName: "Ash Gourd",
    soilType: "loamy",
    description: "White-fleshed vegetable, used in 'Olan' and other dishes.",
    optimalSoilPH: 6.0,
    minimumTemp: 18,
    maximumTemp: 30,
    minimumHumidity: 60,
    maximumHumidity: 85,
    optimalSunlightHours: 6,
    minimumRainfall: 90,
    maximumRainfall: 135,
    commonPests: ["Fruit fly", "Mites"],
    commonDiseases: ["Powdery mildew", "Downy mildew"],
    price: 34
  },
  {
    cropType: "kharif",
    imageLink: "https://th.bing.com/th/id/OIP.xq7yNdgncCgdFrjZMvZtngHaEK?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
    cropName: "Brinjal",
    soilType: "loamy",
    description: "Traditional vegetable found throughout Kerala; several resistant varieties.",
    optimalSoilPH: 6.5,
    minimumTemp: 20,
    maximumTemp: 34,
    minimumHumidity: 60,
    maximumHumidity: 85,
    optimalSunlightHours: 7,
    minimumRainfall: 60,
    maximumRainfall: 120,
    commonPests: ["Fruit borer", "Aphids"],
    commonDiseases: ["Bacterial wilt", "Phomopsis blight"],
    price: 30
  },
  {
    cropType: "kharif",
    imageLink: "https://th.bing.com/th/id/OIP.2BKYdDf9xt18aXxa8oyscAHaE8?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
    cropName: "Green Chilli",
    soilType: "loamy",
    description: "Popular spice and vegetable, vital for Kerala’s curries and chutneys.",
    optimalSoilPH: 6.0,
    minimumTemp: 21,
    maximumTemp: 32,
    minimumHumidity: 60,
    maximumHumidity: 85,
    optimalSunlightHours: 6,
    minimumRainfall: 75,
    maximumRainfall: 135,
    commonPests: ["Aphids", "Thrips"],
    commonDiseases: ["Leaf curl", "Anthracnose"],
    price: 80
  },
  {
    cropType: "kharif",
    imageLink: "https://images.unsplash.com/photo-1465101046530-73398c7f28a1",
    cropName: "Okra",
    soilType: "loamy",
    description: "Also called ‘Lady’s Finger’; staple green vegetable in Kerala.",
    optimalSoilPH: 6.4,
    minimumTemp: 22,
    maximumTemp: 35,
    minimumHumidity: 65,
    maximumHumidity: 85,
    optimalSunlightHours: 7,
    minimumRainfall: 85,
    maximumRainfall: 160,
    commonPests: ["Fruit borer", "Jassids"],
    commonDiseases: ["Powdery mildew", "Yellow vein mosaic"],
    price: 32
  },
  {
    cropType: "kharif",
    imageLink: "https://images.unsplash.com/photo-1465101046530-73398c7f28a1",
    cropName: "Beans",
    soilType: "loamy",
    description: "Cultivated for fresh pods and dry beans, popular in cooler districts.",
    optimalSoilPH: 6.5,
    minimumTemp: 20,
    maximumTemp: 30,
    minimumHumidity: 60,
    maximumHumidity: 85,
    optimalSunlightHours: 8,
    minimumRainfall: 60,
    maximumRainfall: 115,
    commonPests: ["Aphids", "Bean beetle"],
    commonDiseases: ["Anthracnose", "Leaf spot"],
    price: 110
  },
  {
    cropType: "kharif",
    imageLink: "https://images.unsplash.com/photo-1465101046530-73398c7f28a1",
    cropName: "Cowpea",
    soilType: "loamy",
    description: "Short-duration legume, recommended for Kerala’s pulses development program.",
    optimalSoilPH: 6,
    minimumTemp: 20,
    maximumTemp: 34,
    minimumHumidity: 60,
    maximumHumidity: 85,
    optimalSunlightHours: 7,
    minimumRainfall: 60,
    maximumRainfall: 110,
    commonPests: ["Aphids", "Leaf miner"],
    commonDiseases: ["Powdery mildew", "Rust"],
    price: 80
  },
  {
    cropType: "zaid",
    imageLink: "https://images.unsplash.com/photo-1455656678494-4d1b2a4385a7",
    cropName: "Chickpea",
    soilType: "sandy loam",
    description: "Legume crop, mostly grown in the dry zones of Kerala as rabi.",
    optimalSoilPH: 6,
    minimumTemp: 18,
    maximumTemp: 28,
    minimumHumidity: 55,
    maximumHumidity: 80,
    optimalSunlightHours: 7,
    minimumRainfall: 70,
    maximumRainfall: 120,
    commonPests: ["Helicoverpa", "Aphids"],
    commonDiseases: ["Fusarium wilt", "Blight"],
    price: 110
  },
  {
    cropType: "zaid",
    imageLink: "https://images.unsplash.com/photo-1455656678494-4d1b2a4385a7",
    cropName: "Mustard",
    soilType: "loamy",
    description: "Oilseed crop grown as a minor rabi throughout Kerala.",
    optimalSoilPH: 6.2,
    minimumTemp: 15,
    maximumTemp: 30,
    minimumHumidity: 54,
    maximumHumidity: 81,
    optimalSunlightHours: 7,
    minimumRainfall: 60,
    maximumRainfall: 95,
    commonPests: ["Aphids", "Sawfly"],
    commonDiseases: ["Alternaria blight"],
    price: 120
  },
  {
    cropType: "zaid",
    imageLink: "https://images.unsplash.com/photo-1455656678494-4d1b2a4385a7",
    cropName: "Sesame",
    soilType: "loamy",
    description: "Traditional edible oil crop; small-scale in Kerala.",
    optimalSoilPH: 6.2,
    minimumTemp: 20,
    maximumTemp: 32,
    minimumHumidity: 59,
    maximumHumidity: 82,
    optimalSunlightHours: 7,
    minimumRainfall: 65,
    maximumRainfall: 100,
    commonPests: ["Gall midge", "Caterpillar"],
    commonDiseases: ["Leaf spot", "Wilt"],
    price: 110
  },
  {
    cropType: "zaid",
    imageLink: "https://images.unsplash.com/photo-1455656678494-4d1b2a4385a7",
    cropName: "Groundnut",
    soilType: "sandy loam",
    description: "Oilseed, grown in parts of northern Kerala during summer.",
    optimalSoilPH: 6,
    minimumTemp: 22,
    maximumTemp: 34,
    minimumHumidity: 60,
    maximumHumidity: 80,
    optimalSunlightHours: 8,
    minimumRainfall: 60,
    maximumRainfall: 140,
    commonPests: ["Pod borer", "Aphids"],
    commonDiseases: ["Rust", "Leaf spot"],
    price: 120
  },
  {
    cropType: "zaid",
    imageLink: "https://images.unsplash.com/photo-1465101046530-73398c7f28a1",
    cropName: "Onion",
    soilType: "loamy",
    description: "Grown in Kerala’s summer season, in polyhouses and field margins.",
    optimalSoilPH: 6.2,
    minimumTemp: 17,
    maximumTemp: 32,
    minimumHumidity: 60,
    maximumHumidity: 80,
    optimalSunlightHours: 8,
    minimumRainfall: 60,
    maximumRainfall: 110,
    commonPests: ["Thrips", "Onion maggot"],
    commonDiseases: ["Purple blotch", "Downy mildew"],
    price: 55
  },
  {
    cropType: "kharif",
    imageLink: "https://images.unsplash.com/photo-1455656678494-4d1b2a4385a7",
    cropName: "Papaya",
    soilType: "loamy",
    description: "Fast-growing fruit crop, grown widely in homesteads for its sweet fruit.",
    optimalSoilPH: 6.5,
    minimumTemp: 22,
    maximumTemp: 35,
    minimumHumidity: 65,
    maximumHumidity: 90,
    optimalSunlightHours: 7,
    minimumRainfall: 75,
    maximumRainfall: 180,
    commonPests: ["Papaya mealybug", "Fruit fly"],
    commonDiseases: ["Ring spot virus", "Powdery mildew"],
    price: 32
  },
  {
    cropType: "kharif",
    imageLink: "https://images.unsplash.com/photo-1455656678494-4d1b2a4385a7",
    cropName: "Betel Leaf",
    soilType: "loamy",
    description: "Widely used in Kerala rituals and chewing; grown in shade.",
    optimalSoilPH: 6.2,
    minimumTemp: 20,
    maximumTemp: 33,
    minimumHumidity: 65,
    maximumHumidity: 85,
    optimalSunlightHours: 5,
    minimumRainfall: 90,
    maximumRainfall: 130,
    commonPests: ["Scale insects", "Mites"],
    commonDiseases: ["Leaf spot"],
    price: 140
  },
  {
    cropType: "kharif",
    imageLink: "https://images.unsplash.com/photo-1482062364825-616fd23b8fc1",
    cropName: "Vanilla",
    soilType: "loamy",
    description: "Vine spice crop grown under shade, famous for Kerala vanilla essence.",
    optimalSoilPH: 6.5,
    minimumTemp: 19,
    maximumTemp: 30,
    minimumHumidity: 70,
    maximumHumidity: 92,
    optimalSunlightHours: 5,
    minimumRainfall: 120,
    maximumRainfall: 180,
    commonPests: ["Aphids", "Thrips"],
    commonDiseases: ["Root rot", "Anthracnose"],
    price: 7200
  },
  {
    cropType: "kharif",
    imageLink: "https://images.unsplash.com/photo-1482062364825-616fd23b8fc1",
    cropName: "Clove",
    soilType: "lateritic",
    description: "Spice crop, Kerala’s climate is suitable for good flowering.",
    optimalSoilPH: 6.0,
    minimumTemp: 15,
    maximumTemp: 33,
    minimumHumidity: 70,
    maximumHumidity: 92,
    optimalSunlightHours: 6,
    minimumRainfall: 110,
    maximumRainfall: 180,
    commonPests: ["Stem borer", "Leaf miner"],
    commonDiseases: ["Dieback", "Leaf blight"],
    price: 780
  },
  {
    cropType: "kharif",
    imageLink: "https://images.unsplash.com/photo-1482062364825-616fd23b8fc1",
    cropName: "Cinnamon",
    soilType: "loamy",
    description: "Kerala produces cinnamon from home gardens, valued for bark.",
    optimalSoilPH: 6.2,
    minimumTemp: 16,
    maximumTemp: 31,
    minimumHumidity: 70,
    maximumHumidity: 89,
    optimalSunlightHours: 7,
    minimumRainfall: 100,
    maximumRainfall: 160,
    commonPests: ["Leaf miner", "Aphids"],
    commonDiseases: ["Leaf blight"],
    price: 520
  },
  {
    cropType: "kharif",
    imageLink: "https://images.unsplash.com/photo-1482062364825-616fd23b8fc1",
    cropName: "Nutmeg",
    soilType: "loamy",
    description: "Spice tree, producing both nutmeg and mace; grows well in Kerala.",
    optimalSoilPH: 6.2,
    minimumTemp: 20,
    maximumTemp: 32,
    minimumHumidity: 70,
    maximumHumidity: 90,
    optimalSunlightHours: 7,
    minimumRainfall: 130,
    maximumRainfall: 180,
    commonPests: ["Mealy bugs", "Shoot borer"],
    commonDiseases: ["Fruit rot", "Leaf spot"],
    price: 360
  },
  {
    cropType: "perennial",
    imageLink: "https://images.unsplash.com/photo-1517487881405-ec872a1f1752",
    cropName: "Turmeric",
    soilType: "loamy",
    description: "Rhizome spice crop, grown extensively for food and ayurveda.",
    optimalSoilPH: 6.5,
    minimumTemp: 22,
    maximumTemp: 33,
    minimumHumidity: 70,
    maximumHumidity: 92,
    optimalSunlightHours: 7,
    minimumRainfall: 100,
    maximumRainfall: 170,
    commonPests: ["Shoot borer", "Rhizome scale"],
    commonDiseases: ["Leaf spot", "Rhizome rot"],
    price: 115
  },
  {
    cropType: "perennial",
    imageLink: "https://images.unsplash.com/photo-1517487881405-ec872a1f1752",
    cropName: "Ginger",
    soilType: "loamy",
    description: "Widely grown spice crop; Kerala ginger is exported worldwide.",
    optimalSoilPH: 6.2,
    minimumTemp: 21,
    maximumTemp: 30,
    minimumHumidity: 70,
    maximumHumidity: 90,
    optimalSunlightHours: 7,
    minimumRainfall: 90,
    maximumRainfall: 160,
    commonPests: ["Shoot borer", "Rhizome fly"],
    commonDiseases: ["Soft rot", "Leaf spot"],
    price: 90
  },
  {
    cropType: "zaid",
    imageLink: "https://images.unsplash.com/photo-1517487881405-ec872a1f1752",
    cropName: "Drumstick",
    soilType: "sandy loam",
    description: "Fast-growing tree, pods are nutritionally rich and highly preferred.",
    optimalSoilPH: 6.5,
    minimumTemp: 20,
    maximumTemp: 38,
    minimumHumidity: 55,
    maximumHumidity: 80,
    optimalSunlightHours: 8,
    minimumRainfall: 60,
    maximumRainfall: 130,
    commonPests: ["Flies", "Borers"],
    commonDiseases: ["Powdery mildew", "Root rot"],
    price: 38
  },
  {
    cropType: "kharif",
    imageLink: "https://images.unsplash.com/photo-1517487881405-ec872a1f1752",
    cropName: "Amaranthus",
    soilType: "loamy",
    description: "Leafy vegetable, well suited for Kerala’s homestead gardens.",
    optimalSoilPH: 6.2,
    minimumTemp: 18,
    maximumTemp: 32,
    minimumHumidity: 60,
    maximumHumidity: 80,
    optimalSunlightHours: 7,
    minimumRainfall: 100,
    maximumRainfall: 150,
    commonPests: ["Aphids", "Leafminer"],
    commonDiseases: ["Downy mildew", "Leaf spot"],
    price: 40
  },
  {
    cropType: "kharif",
    imageLink: "https://images.unsplash.com/photo-1482062364825-616fd23b8fc1",
    cropName: "Plantain",
    soilType: "loamy",
    description: "Non-dessert banana; used especially for ‘banana chips’.",
    optimalSoilPH: 6,
    minimumTemp: 22,
    maximumTemp: 35,
    minimumHumidity: 60,
    maximumHumidity: 92,
    optimalSunlightHours: 7,
    minimumRainfall: 100,
    maximumRainfall: 220,
    commonPests: ["Banana weevil", "Aphids"],
    commonDiseases: ["Sigatoka leaf spot", "Wilt"],
    price: 45
  },
  {
    cropType: "kharif",
    imageLink: "https://images.unsplash.com/photo-1521058798685-736c97211b3d",
    cropName: "Little Millet",
    soilType: "loamy",
    description: "Millet grown in districts like Palakkad for food and fodder.",
    optimalSoilPH: 6.5,
    minimumTemp: 20,
    maximumTemp: 32,
    minimumHumidity: 60,
    maximumHumidity: 85,
    optimalSunlightHours: 8,
    minimumRainfall: 80,
    maximumRainfall: 130,
    commonPests: ["Stem borer", "Leaf spot"],
    commonDiseases: ["Blast", "Leaf spot"],
    price: 95
  },
  {
    cropType: "kharif",
    imageLink: "https://images.unsplash.com/photo-1521058798685-736c97211b3d",
    cropName: "Kodo Millet",
    soilType: "loamy",
    description: "Another minor millet with local value; grown in select drylands.",
    optimalSoilPH: 6.5,
    minimumTemp: 19,
    maximumTemp: 34,
    minimumHumidity: 60,
    maximumHumidity: 85,
    optimalSunlightHours: 8,
    minimumRainfall: 70,
    maximumRainfall: 120,
    commonPests: ["Shoot fly", "Leaf caterpillar"],
    commonDiseases: ["Leaf spot", "Rust"],
    price: 80
  },
  {
    cropType: "kharif",
    imageLink: "https://images.unsplash.com/photo-1521058798685-736c97211b3d",
    cropName: "Maize",
    soilType: "loamy",
    description: "Field crop, mostly for cattle feed and fresh consumption.",
    optimalSoilPH: 6.8,
    minimumTemp: 19,
    maximumTemp: 34,
    minimumHumidity: 60,
    maximumHumidity: 85,
    optimalSunlightHours: 8,
    minimumRainfall: 70,
    maximumRainfall: 145,
    commonPests: ["Stem borer", "Aphids"],
    commonDiseases: ["Downy mildew", "Leaf blight"],
    price: 35
  },
  {
    cropType: "kharif",
    imageLink: "https://images.unsplash.com/photo-1521058798685-736c97211b3d",
    cropName: "Ragi",
    soilType: "loamy",
    description: "Finger millet, grown both as food and for nutritional value.",
    optimalSoilPH: 6.2,
    minimumTemp: 18,
    maximumTemp: 34,
    minimumHumidity: 62,
    maximumHumidity: 84,
    optimalSunlightHours: 8,
    minimumRainfall: 60,
    maximumRainfall: 125,
    commonPests: ["Stem borer", "Aphid"],
    commonDiseases: ["Blast", "Leaf spot"],
    price: 88
  },
  {
    cropType: "perennial",
    imageLink: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    cropName: "Watermelon",
    soilType: "sandy",
    description: "Seasonal fruit crop, grown especially in summer near rivers and backwaters.",
    optimalSoilPH: 6.6,
    minimumTemp: 21,
    maximumTemp: 32,
    minimumHumidity: 60,
    maximumHumidity: 82,
    optimalSunlightHours: 8,
    minimumRainfall: 70,
    maximumRainfall: 120,
    commonPests: ["Fruit fly", "Red pumpkin beetle"],
    commonDiseases: ["Powdery mildew", "Downy mildew"],
    price: 30
  },
  {
    cropType: "kharif",
    imageLink: "https://images.unsplash.com/photo-1517487881405-ec872a1f1752",
    cropName: "Tomato",
    soilType: "loamy",
    description: "Widely grown in Kerala, with many disease-resistant local varieties.",
    optimalSoilPH: 6.5,
    minimumTemp: 18,
    maximumTemp: 34,
    minimumHumidity: 60,
    maximumHumidity: 82,
    optimalSunlightHours: 8,
    minimumRainfall: 80,
    maximumRainfall: 120,
    commonPests: ["Fruit borer", "Whitefly"],
    commonDiseases: ["Blight", "Leaf curl"],
    price: 55
  }
]

const connectDB=async()=>{
    try{
        mongoose.connection.on('connected',()=>console.log('Database connected'))
        await mongoose.connect(`${process.env.MONGODB_URI}/agrosense`)
        
    }catch (error){
        console.log(error.message);
        
    }
}

const insertCrops = async (crops) => {
  try {
    const result = await Cropdata.insertMany(crops);
    console.log(`Added ${result.length} crops`);
  } catch (error) {
    console.error("Error inserting crops:", error);
    throw error;
  }
};

const run = async () => {
  try {
    await connectDB();
    const count = await Cropdata.countDocuments();
    // if (count === 0) {
    //   await insertCrops(keralaCrops);
    // } else {
    //   console.log(`Crops already exist in the database (${count} records)`);
    // }
    await Cropdata.deleteMany({});
    console.log("All existing crops deleted");
    await insertCrops(keralaCrops);
    console.log("Crops inserted successfully");
  } catch (e) {
    console.error("Operation failed:", e);
  } finally {
    await mongoose.disconnect();
    console.log("MongoDB disconnected");
  }
};

run();
